version: 2.1
orbs:
  okareo-orb: okareo/okareo-orb@0.0.1
workflows:
  use-my-orb:
    jobs:
      - okareo-orb/run_test
      - command-test:
        docker:
          - image: cimg/base:current
        steps:
          - checkout
          - okareo-orb/setup
          - okareo-orb/version
          - okareo-orb/validate